steps:
- name: 'gcr.io/cloud-builders/gradle'
  args: ['bootJar']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/spring-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/spring-app']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'service.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=spinnaker-test-1'
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'deployment.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=spinnaker-test-1'
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/spring-app-deployment', 'spring-app=gcr.io/$PROJECT_ID/spring-app']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=spinnaker-test-1'
images:
- 'gcr.io/$PROJECT_ID/spring-app'

