steps:
- name: 'gcr.io/cloud-builders/gradle'
  args: ['bootJar']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/spring-app', '.']
images:
- 'gcr.io/$PROJECT_ID/spring-app'

