steps:
- name: 'gcr.io/cloud-builders/mvn:3.5.0-jdk-8'
  args: ['package']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile-maven', '-t', 'gcr.io/$PROJECT_ID/spring-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/spring-app']
images:
- 'gcr.io/$PROJECT_ID/spring-app'

